### ISSUE TITLE
Init.sh requires nightly-2020-10-05

### ISSUE THREAD

**Issue by paulhealy** [paritytech/canvas-node#27]
set -e

echo "*** Initializing WASM build environment"

if [ -z $CI_PROJECT_NAME ] ; then
   rustup update nightly
   rustup update nightly-2020-10-05
   rustup update stable
fi

rustup target add wasm32-unknown-unknown --toolchain nightly
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-05

**Comment by NukeManDan** [comment]
This should be resolved by using v3 of substrate tooling throughout your codebase. Also of note:

> [Ink Announcement](https://matrix.to/#/!OEoEzWHbyVSzzkIWQw:matrix.parity.io/$-YMLT_-kQF2BsgzcVDpI9qSra_MD29RLW2dIdwh9X-A?via=matrix.parity.io&via=matrix.org&via=web3.foundation)
> Currently many users are facing incompatibility issues using ink! 3.0-rc3 with Substrate 3.0 including the contracts-pallet 3.0 when trying to interact with their smart contracts via the Canvas UI. This is due to a missing adjustment for smart contract instantiation introduced in the most recent contracts-pallet version 3.0. The issue is on top of our priority list and we try to resolve it asap.
> 
>In the meantime please use the Polkadot JS Apps interface instead of Canvas UI since it already has support for the new contracts-pallet instantiation APIs.
