### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/canvas-node#33]
Which tag of this canvas-node repo should I use with v3.0.0-rc3 ink smart contract?

**Comment by NukeManDan** [comment]
Hey - [subport](https://github.com/paritytech/subport) is best to get rapid attention :) I think you saw on the ink! announcements matrix channel about this? 
> Announcement
> Currently many users are facing incompatibility issues using ink! 3.0-rc3 with Substrate 3.0 including the contracts-pallet 3.0 when trying to interact with their smart contracts via the Canvas UI. This is due to a missing adjustment for smart contract instantiation introduced in the most recent contracts-pallet version 3.0. The issue is on top of our priority list and we try to resolve it asap.

> In the meantime please use the Polkadot JS Apps interface instead of Canvas UI since it already has support for the new contracts-pallet instantiation APIs.
