### ISSUE TITLE
Cannot deploy contract

### ISSUE THREAD

**Issue by naps62** [paritytech/canvas-node#34]
When trying to deploy a contract via `@polkadot/api`, I get an error `Cannot read property 'batch' of undefined`

According to https://github.com/polkadot-js/api/issues/3268, this seems to be caused by the utility module being missing from the runtime, if I understood correctly

**Comment by ascjones** [comment]
Can you show the code you are using to deploy the contract?

**Comment by naps62** [comment]
It seems this is now working. Not sure what I changed, other than the fact that I was tired yesterday, from trying around random things in desperation.

This version is currently working. I just need to understand a bit more how the endowment works, since these values were put at random to see what sticks, but at least the deploy itself is working

(I'm building this deploy script while `cargo contract deploy` isn't working, and also so that I can learn how these pieces work

```js
const { ApiPromise, WsProvider } =require("@polkadot/api");
const { Keyring } = require("@polkadot/keyring");
const { createTestKeyring } = require("@polkadot/keyring/testing");
const { CodePromise } = require("@polkadot/api-contract");
const fs = require("fs");

const ABI = require("../contracts/world/hello/ink/metadata.json");
const WASM = fs.readFileSync("../contracts/hello/target/ink/world.wasm");

(async() => {
  const provider = new WsProvider("ws://127.0.0.1:9944");
  const api = await ApiPromise.create({ provider });

  const keyring = new Keyring({ type: 'sr25519', ss58Format: 42 });
  const alice = keyring.addFromUri('//Alice', { name: 'Alice' });
  const account = (await createTestKeyring().getPairs())[0];

  const code = new CodePromise(api, ABI, WASM)

  code.tx.default({ gasLimit: 100000 * 1000000, salt: null, value: 2230000000000000 })
  .signAndSend(alice, (result) => {
    if (result.status.isInBlock || result.status.isFinalized) {
      // here we have an additional field in the result, containing the blueprint
      blueprint = result.blueprint;
    }
  })
})()
```
