### ISSUE TITLE
Keep Persistent Contract State 

### ISSUE THREAD

**Issue by ILoomans** [paritytech/canvas-node#44]
**Question**
 I was able to deploy an ink contract, query, transact on it etc. The issue is that i am losing the ability to interact with the smart contract around 2 hours after it is deployed. I understand that this is a persistence issue. 

However i did start the node with the following command:

canvas --dev #(instead of canvas --dev --tmp)

Which i understand should keep the state.

Deploy smart contract with polkadot.js or canvas-ui
Interact with it for 2 hours and then sometime after any interaction will fail

Here is a snippit of the code i am using to deploy the contract and then interact with it, i also commented where the error occurs after two hours. 

https://gist.github.com/ILoomans/e8cb55c72f8b1b274da7fc375cb5a6ba

Hope someone can help!

**Comment by cmichi** [comment]
@ILoomans This is most probably an issue with contract state rent. [See here for more info](https://substrate.dev/substrate-contracts-workshop/#/0/troubleshooting?id=contract-state-rent).

You can verify that it's an issue with the contract running out of funds to pay rent and thus being evicted by deploying the contract via https://polkadot.js.org/apps/#/contracts. This UI will show you a rent projection of how long the contract will probably survive with its current funding:

![download](https://user-images.githubusercontent.com/241530/117951030-0d5f4f80-b314-11eb-9432-8f66c594a30f.png)

For testing the easiest fix is to increase your initial endowment to the contract.

Was this your issue?

**Comment by ILoomans** [comment]
Great! Yes i do think this is the problem, i had a ink function that returned the contract balance and was curious why it was decreasing! Ill keep you posted if this works.

**Comment by cmichi** [comment]
I'm closing this, since it seems to be resolved. Feel free to reopen/create another ticket if you still have this issue.
