### ISSUE TITLE
tags v0.1.8 install failed

### ISSUE THREAD

**Issue by luo4lu** [paritytech/canvas-node#56]
![image](https://user-images.githubusercontent.com/27767582/122876449-1ce8a400-d368-11eb-9e1c-322e86a1c75c.png)
source code build failed。

**Comment by cmichi** [comment]
@luo4lu Could you retry with the latest release please?

```
cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.9 --force --locked
```

**Comment by cmichi** [comment]
I'm closing the issue, since I think it should be resolved with the latest release. Feel free to reopen otherwise.
